"""Copy for the landing page, one entry per language."""

SITE = "https://minutesback.github.io/multi-tofu/"
REPO = "https://github.com/MinutesBack/multi-tofu"
RELEASES = REPO + "/releases"
DOWNLOAD = REPO + "/releases/latest"
VERSION = "0.4.1"

LANGS = ["en", "fr", "es", "pt"]
LANG_NAMES = {"en": "English", "fr": "Français", "es": "Español", "pt": "Português"}

CONTENT = {
"en": {
 "locale": "en_US",
 "title": "Dofus Multi-Account Switcher for Mac | Multi-Tofu",
 "description": "Free open source Dofus multi-account tool for macOS. Switch clients instantly with F1, a radial character wheel and team rotation. Apple Silicon and Intel.",
 "tagline": "Play Dofus multi-account on a Mac without fighting your windows.",
 "lede": "Multi-Tofu switches between your Dofus clients with a single key. It reads each window and puts the right character in front, so you stop hunting through Mission Control mid fight.",
 "download": "Download for macOS",
 "download_sub": "Free and open source. Apple Silicon and Intel. Version " + VERSION + ".",
 "source": "View the source",
 "features_title": "What it does",
 "features": [
   ("Instant switch", "F1 and F2 walk your rotation, F3 jumps straight back to your leader. One key, no mouse, no Mission Control."),
   ("Character wheel", "Hold Option and a wheel appears under your cursor with a class icon for every character. Move, release, that client is in front."),
   ("Teams", "Split your characters into teams and cycle only inside the active one. Useful when you run a dungeon group and leave the rest parked."),
   ("Direct keys", "Bind one fixed key per character. F5 always goes to your Iop, whatever the rotation is doing."),
   ("Real names", "Character names are read live from the game window. Nothing to type in, nothing to keep updated."),
   ("Four languages", "English, French, Spanish and Portuguese, following your system language."),
   ("Roles", "Tag each character as tank, healer, damage, support or scout and its wheel segment gets a coloured rim. Past five clients you read colour faster than names."),
   ("Peek", "Hold one key to look at another client, release and you are back where you were, rotation position intact."),
   ("Order by number", "Type a position to place a character. Sorting a team by initiative is six keystrokes, not twenty arrow clicks."),
   ("It stays saved", "Order, teams, roles, leader and every shortcut are written to disk as you change them, keyed by character. Come back next week and it is as you left it."),
   ("Stays out of the way", "It opens Settings the first time so you can set it up, then sits quietly in the menu bar. Once it is running it does not keep coming back to the front, even when the Ankama Launcher relaunches it."),
   ("One key, one action", "Assigning a key that another shortcut holds frees it there. Two actions on one key means one of them silently never fires."),
   ("There when you are", "Start it at login in one click, so it is already running when you open the Ankama Launcher. Idle it costs nothing, with no client open it never even asks the system about windows."),
   ("Only the client you are on", "Switch on hiding and every other client disappears while you play the one in front. Nothing peeks around the edges, Command Tab stays readable, and they all come back the moment you switch to them."),
 ],
 "names_title": "It learns your characters by itself",
 "names_body": "You never type a character name. Multi-Tofu reads the Dofus window title, so the moment a character logs in their real name appears in the wheel, in the menu bar and in the settings list. A client that is open but still sitting on the login screen has no character on it yet, so it shows as Account 1, Account 2 and so on. Those stay clickable in the menu, so you can jump to one and log it in, but they are kept out of the F1 rotation. A keypress never lands you on a window with no character on it.",
 "install_title": "Install in about a minute",
 "steps": [
   ("Download and unzip", "Grab the zip from the releases page and drag Multi-Tofu into your Applications folder."),
   ("Right click, Open", "The app is not signed with a paid Apple developer account, so the first launch needs a right click then Open. After that it opens normally."),
   ("Allow Accessibility", "macOS asks once. Multi-Tofu needs it to read window titles and to hear your shortcuts. Switch it on and the shortcuts come alive a couple of seconds later, no restart."),
   ("Updating later", "An app signed without a paid Apple developer account gets a new signature with every release, so macOS stops recognising it and your shortcuts go quiet while the switch still looks on. Open Settings and click Fix access. It resets the record and macOS asks again."),
 ],
 "keys_title": "Default shortcuts",
 "keys": [("Next character", "F1"), ("Previous character", "F2"), ("Focus leader", "F3"),
          ("Rescan windows", "F4"), ("Character wheel", "hold Option"), ("Peek at another client", "hold `"), ("Open settings", "Control + F1")],
 "keys_note": "All rebindable. Shortcuts are stored as physical keycodes, so they keep working if you switch between AZERTY and QWERTY.",
 "safe_title": "It does not automate anything",
 "safe_body": "Multi-Tofu brings windows to the front. That is the whole feature. There is no bot, no packet reading, no memory injection, and no broadcasting one keystroke to several clients at once. Every action still comes from you, in one client at a time. The code is public, so you do not have to take that on trust.",
 "why_title": "Why this exists",
 "why_body": "The Windows crowd has Dosoft and Organizer. On a Mac there was nothing, and the closest project was archived in August 2026. Dosoft is Apache 2.0 but built entirely on the Win32 API, so none of it ports. This is a fresh implementation on the macOS Accessibility API, a CGEventTap for the shortcuts, and AppKit for the wheel, reusing the class artwork and the feature design under that licence.",
 "compat_title": "Requirements",
 "compat": ["macOS 12 or later", "Dofus 3 (Unity), the client the Ankama Launcher installs",
            "Apple Silicon or Intel, one universal build", "Windowed or borderless mode, the wheel does not draw over exclusive fullscreen"],
 "footer_docs": "Documentation",
 "footer_issues": "Report a problem",
 "footer_licence": "Apache 2.0",
 "disclaimer": "Multi-Tofu is not affiliated with, endorsed by, or sponsored by Ankama Games. DOFUS and all related names and artwork are the property of Ankama Games.",
 "alt_logo": "The Multi-Tofu app icon, a small round cream bird on a purple background",
 "alt_wheel": "The Multi-Tofu character wheel, six Dofus characters in a circle with the hovered one highlighted",
 "alt_prefs": "The Multi-Tofu settings window showing shortcuts and the detected character list",
},
"fr": {
 "locale": "fr_FR",
 "title": "Multicompte Dofus sur Mac | Multi-Tofu",
 "description": "Outil multicompte Dofus gratuit et open source pour macOS. Basculez entre vos clients avec F1, roue des personnages et équipes. Apple Silicon et Intel.",
 "tagline": "Jouer Dofus en multicompte sur Mac sans se battre avec ses fenêtres.",
 "lede": "Multi-Tofu bascule entre vos clients Dofus d'une seule touche. Il lit chaque fenêtre et met le bon personnage devant, fini la chasse dans Mission Control en plein combat.",
 "download": "Télécharger pour macOS",
 "download_sub": "Gratuit et open source. Apple Silicon et Intel. Version " + VERSION + ".",
 "source": "Voir le code source",
 "features_title": "Ce que ça fait",
 "features": [
   ("Bascule instantanée", "F1 et F2 parcourent votre rotation, F3 revient directement sur votre chef. Une touche, sans souris, sans Mission Control."),
   ("Roue des personnages", "Maintenez Option, une roue apparaît sous le curseur avec l'icône de classe de chaque personnage. Bougez, relâchez, le client est devant."),
   ("Équipes", "Répartissez vos personnages et ne tournez que dans l'équipe active. Pratique quand vous montez un donjon et laissez le reste en pause."),
   ("Touches directes", "Une touche fixe par personnage. F5 va toujours sur votre Iop, quelle que soit la rotation."),
   ("Vrais pseudos", "Les noms sont lus en direct dans la fenêtre du jeu. Rien à saisir, rien à tenir à jour."),
   ("Quatre langues", "Anglais, français, espagnol et portugais, calées sur la langue de votre système."),
   ("Rôles", "Marquez chaque personnage en tank, soigneur, dégâts, soutien ou éclaireur et sa part de roue prend un liseré de couleur. Au-delà de cinq clients, la couleur se lit plus vite qu'un nom."),
   ("Coup d'oeil", "Maintenez une touche pour regarder un autre client, relâchez et vous revenez exactement où vous étiez, place dans la rotation comprise."),
   ("Ordre au clavier", "Tapez un numéro pour placer un personnage. Trier une équipe par initiative prend six frappes, pas vingt clics sur une flèche."),
   ("Tout est conservé", "Ordre, équipes, rôles, chef et chaque raccourci sont écrits sur le disque au fil de vos changements, par personnage. Revenez la semaine prochaine, rien n'a bougé."),
   ("Reste discret", "Il ouvre les réglages la première fois pour l'installation, puis se fait oublier dans la barre de menus. Une fois lancé il ne revient pas au premier plan, même quand le Launcher Ankama le relance."),
   ("Une touche, une action", "Attribuer une touche déjà prise la libère chez l'autre action. Deux actions sur une touche, c'est une des deux qui ne se déclenche jamais."),
   ("Déjà là quand vous arrivez", "Lancement à l'ouverture de session en un clic, l'app tourne déjà quand vous ouvrez l'Ankama Launcher. Au repos elle ne coûte rien, sans client ouvert elle n'interroge même pas le système."),
   ("Seul le client où vous êtes", "Activez le masquage et tous les autres clients disparaissent pendant que vous jouez celui du dessus. Plus rien ne dépasse sur les bords, Command Tab reste lisible, et ils reviennent dès que vous passez dessus."),
 ],
 "names_title": "Il reconnaît vos personnages tout seul",
 "names_body": "Vous ne saisissez jamais un pseudo. Multi-Tofu lit le titre de la fenêtre Dofus, donc dès qu'un personnage se connecte son vrai nom apparaît dans la roue, dans la barre des menus et dans les réglages. Un client ouvert mais resté sur l'écran de connexion n'a pas encore de personnage, il s'affiche donc en Compte 1, Compte 2 et ainsi de suite. Ces entrées restent cliquables dans le menu, vous pouvez y aller pour vous connecter, mais elles sont exclues de la rotation F1. Une touche ne vous envoie jamais sur une fenêtre sans personnage.",
 "install_title": "Installation en une minute",
 "steps": [
   ("Télécharger et décompresser", "Récupérez le zip sur la page des versions et glissez Multi-Tofu dans votre dossier Applications."),
   ("Clic droit, Ouvrir", "L'app n'est pas signée avec un compte développeur Apple payant, le premier lancement demande donc un clic droit puis Ouvrir. Ensuite elle s'ouvre normalement."),
   ("Autoriser l'Accessibilité", "macOS le demande une fois. Multi-Tofu en a besoin pour lire les titres de fenêtres et entendre vos raccourcis. Activez-le, les raccourcis s'allument deux secondes plus tard, sans redémarrage."),
   ("Mettre à jour plus tard", "Une app signée sans compte développeur Apple payant change de signature à chaque version, macOS ne la reconnaît donc plus et vos raccourcis se taisent alors que l'interrupteur paraît toujours actif. Ouvrez les réglages et cliquez sur Réparer l'accès. Cela réinitialise l'autorisation et macOS redemande."),
 ],
 "keys_title": "Raccourcis par défaut",
 "keys": [("Personnage suivant", "F1"), ("Personnage précédent", "F2"), ("Aller au chef", "F3"),
          ("Rechercher les fenêtres", "F4"), ("Roue des personnages", "maintenir Option"), ("Coup d'oeil sur un autre client", "maintenir ²"), ("Ouvrir les réglages", "Control + F1")],
 "keys_note": "Tout est modifiable. Les raccourcis sont enregistrés comme codes de touches physiques, ils survivent donc à un passage AZERTY vers QWERTY.",
 "safe_title": "Aucune automatisation",
 "safe_body": "Multi-Tofu met des fenêtres au premier plan. C'est toute la fonctionnalité. Pas de bot, pas de lecture de paquets, pas d'injection mémoire, et aucune diffusion d'une frappe vers plusieurs clients à la fois. Chaque action vient toujours de vous, dans un seul client à la fois. Le code est public, vous n'avez pas à nous croire sur parole.",
 "why_title": "Pourquoi ce projet",
 "why_body": "Sous Windows il y a Dosoft et Organizer. Sur Mac il n'y avait rien, et le projet le plus proche a été archivé en août 2026. Dosoft est en Apache 2.0 mais entièrement bâti sur l'API Win32, donc rien ne se transpose. Voici une implémentation neuve sur l'API d'Accessibilité macOS, un CGEventTap pour les raccourcis et AppKit pour la roue, en réutilisant les visuels de classe et le design fonctionnel sous cette licence.",
 "compat_title": "Prérequis",
 "compat": ["macOS 12 ou plus récent", "Dofus 3 (Unity), le client installé par l'Ankama Launcher",
            "Apple Silicon ou Intel, une seule version universelle", "Mode fenêtré ou sans bordure, la roue ne s'affiche pas au-dessus du plein écran exclusif"],
 "footer_docs": "Documentation",
 "footer_issues": "Signaler un problème",
 "footer_licence": "Apache 2.0",
 "disclaimer": "Multi-Tofu n'est ni affilié à Ankama Games, ni approuvé ni sponsorisé par eux. DOFUS et tous les noms et visuels associés appartiennent à Ankama Games.",
 "alt_logo": "L'icône de Multi-Tofu, un petit oiseau rond crème sur fond violet",
 "alt_wheel": "La roue des personnages de Multi-Tofu, six personnages Dofus en cercle avec celui survolé mis en avant",
 "alt_prefs": "La fenêtre de réglages de Multi-Tofu avec les raccourcis et la liste des personnages détectés",
},
"es": {
 "locale": "es_ES",
 "title": "Multicuenta de Dofus para Mac | Multi-Tofu",
 "description": "Herramienta multicuenta de Dofus gratuita y de código abierto para macOS. Cambia de cliente con F1, rueda de personajes y equipos. Apple Silicon e Intel.",
 "tagline": "Juega Dofus multicuenta en Mac sin pelearte con las ventanas.",
 "lede": "Multi-Tofu cambia entre tus clientes de Dofus con una sola tecla. Lee cada ventana y pone delante al personaje correcto, se acabó buscar en Mission Control en mitad de un combate.",
 "download": "Descargar para macOS",
 "download_sub": "Gratis y de código abierto. Apple Silicon e Intel. Versión " + VERSION + ".",
 "source": "Ver el código",
 "features_title": "Qué hace",
 "features": [
   ("Cambio instantáneo", "F1 y F2 recorren tu rotación, F3 vuelve directo a tu líder. Una tecla, sin ratón, sin Mission Control."),
   ("Rueda de personajes", "Mantén Opción y aparece una rueda bajo el cursor con el icono de clase de cada personaje. Mueve, suelta, ese cliente pasa al frente."),
   ("Equipos", "Divide tus personajes en equipos y rota solo dentro del activo. Útil cuando montas una mazmorra y dejas el resto aparcado."),
   ("Teclas directas", "Una tecla fija por personaje. F5 siempre va a tu Iop, haga lo que haga la rotación."),
   ("Nombres reales", "Los nombres se leen en vivo de la ventana del juego. Nada que escribir, nada que mantener."),
   ("Cuatro idiomas", "Inglés, francés, español y portugués, según el idioma de tu sistema."),
   ("Roles", "Marca cada personaje como tanque, sanador, daño, apoyo o explorador y su porción de la rueda recibe un borde de color. Pasados cinco clientes, el color se lee más rápido que el nombre."),
   ("Vistazo", "Mantén una tecla para mirar otro cliente, suéltala y vuelves justo donde estabas, con tu posición en la rotación intacta."),
   ("Orden por número", "Escribe una posición para colocar un personaje. Ordenar un equipo por iniciativa son seis pulsaciones, no veinte clics en una flecha."),
   ("Se guarda solo", "Orden, equipos, roles, líder y cada atajo se escriben en disco según los cambias, por personaje. Vuelve la semana que viene y sigue igual."),
   ("No molesta", "Abre los ajustes la primera vez para configurarlo y luego se queda callado en la barra de menús. Una vez en marcha no vuelve a primer plano, ni cuando el Launcher de Ankama lo reabre."),
   ("Una tecla, una acción", "Asignar una tecla que ya tiene otro atajo se la quita a ese. Dos acciones en una tecla significa que una nunca se activa."),
   ("Ahí cuando llegas", "Arranca al iniciar sesión con un clic, así ya está lista cuando abres el Ankama Launcher. En reposo no cuesta nada, sin ningún cliente abierto ni siquiera consulta al sistema."),
   ("Solo el cliente en el que estás", "Activa el ocultado y los demás clientes desaparecen mientras juegas el de delante. Nada asoma por los bordes, Command Tab sigue legible y vuelven en cuanto cambias a ellos."),
 ],
 "names_title": "Reconoce tus personajes solo",
 "names_body": "Nunca escribes un nombre. Multi-Tofu lee el título de la ventana de Dofus, así que en cuanto un personaje inicia sesión su nombre real aparece en la rueda, en la barra de menús y en los ajustes. Un cliente abierto pero todavía en la pantalla de conexión no tiene personaje, así que se muestra como Cuenta 1, Cuenta 2 y así. Siguen siendo clicables en el menú, puedes ir a conectarte, pero quedan fuera de la rotación de F1. Una pulsación nunca te lleva a una ventana sin personaje.",
 "install_title": "Instalación en un minuto",
 "steps": [
   ("Descargar y descomprimir", "Coge el zip de la página de versiones y arrastra Multi-Tofu a tu carpeta Aplicaciones."),
   ("Clic derecho, Abrir", "La app no está firmada con una cuenta de desarrollador de Apple de pago, así que la primera vez hace falta clic derecho y Abrir. Después se abre con normalidad."),
   ("Permitir Accesibilidad", "macOS lo pide una vez. Multi-Tofu la necesita para leer los títulos de ventana y oír tus atajos. Actívala y los atajos arrancan un par de segundos después, sin reiniciar."),
   ("Actualizar más adelante", "Una app firmada sin una cuenta de desarrollador de Apple de pago cambia de firma en cada versión, así que macOS deja de reconocerla y tus atajos se callan aunque el interruptor siga pareciendo activo. Abre los ajustes y pulsa Reparar el acceso. Reinicia el permiso y macOS vuelve a preguntar."),
 ],
 "keys_title": "Atajos por defecto",
 "keys": [("Personaje siguiente", "F1"), ("Personaje anterior", "F2"), ("Ir al líder", "F3"),
          ("Buscar ventanas", "F4"), ("Rueda de personajes", "mantener Opción"), ("Vistazo a otro cliente", "mantener `"), ("Abrir ajustes", "Control + F1")],
 "keys_note": "Todo se puede reasignar. Los atajos se guardan como códigos de tecla física, así que siguen funcionando si cambias entre AZERTY y QWERTY.",
 "safe_title": "No automatiza nada",
 "safe_body": "Multi-Tofu trae ventanas al frente. Esa es toda la función. No hay bot, ni lectura de paquetes, ni inyección de memoria, ni difusión de una pulsación a varios clientes a la vez. Cada acción sigue viniendo de ti, en un cliente cada vez. El código es público, no hace falta que te fíes de nuestra palabra.",
 "why_title": "Por qué existe",
 "why_body": "En Windows están Dosoft y Organizer. En Mac no había nada, y el proyecto más parecido se archivó en agosto de 2026. Dosoft es Apache 2.0 pero está construido enteramente sobre la API Win32, así que nada se puede portar. Esta es una implementación nueva sobre la API de Accesibilidad de macOS, un CGEventTap para los atajos y AppKit para la rueda, reutilizando el arte de clases y el diseño funcional bajo esa licencia.",
 "compat_title": "Requisitos",
 "compat": ["macOS 12 o posterior", "Dofus 3 (Unity), el cliente que instala el Ankama Launcher",
            "Apple Silicon o Intel, una sola compilación universal", "Modo ventana o sin bordes, la rueda no se dibuja sobre pantalla completa exclusiva"],
 "footer_docs": "Documentación",
 "footer_issues": "Informar de un problema",
 "footer_licence": "Apache 2.0",
 "disclaimer": "Multi-Tofu no está afiliado a Ankama Games, ni respaldado ni patrocinado por ellos. DOFUS y todos los nombres e imágenes asociados son propiedad de Ankama Games.",
 "alt_logo": "El icono de Multi-Tofu, un pajarito redondo color crema sobre fondo morado",
 "alt_wheel": "La rueda de personajes de Multi-Tofu, seis personajes de Dofus en círculo con el señalado resaltado",
 "alt_prefs": "La ventana de ajustes de Multi-Tofu con los atajos y la lista de personajes detectados",
},
"pt": {
 "locale": "pt_BR",
 "title": "Multiconta de Dofus para Mac | Multi-Tofu",
 "description": "Ferramenta multiconta de Dofus gratuita e open source para macOS. Troque de cliente com F1, roda de personagens e times. Apple Silicon e Intel.",
 "tagline": "Jogue Dofus multiconta no Mac sem brigar com as janelas.",
 "lede": "O Multi-Tofu troca entre seus clientes do Dofus com uma tecla só. Ele lê cada janela e coloca o personagem certo na frente, acabou a caça no Mission Control no meio do combate.",
 "download": "Baixar para macOS",
 "download_sub": "Grátis e open source. Apple Silicon e Intel. Versão " + VERSION + ".",
 "source": "Ver o código",
 "features_title": "O que faz",
 "features": [
   ("Troca instantânea", "F1 e F2 percorrem sua rotação, F3 volta direto para o líder. Uma tecla, sem mouse, sem Mission Control."),
   ("Roda de personagens", "Segure Option e uma roda aparece no cursor com o ícone de classe de cada personagem. Mova, solte, aquele cliente vem para a frente."),
   ("Times", "Divida seus personagens em times e gire só dentro do ativo. Útil quando você monta uma dungeon e deixa o resto parado."),
   ("Teclas diretas", "Uma tecla fixa por personagem. F5 sempre vai no seu Iop, faça o que fizer a rotação."),
   ("Nomes reais", "Os nomes são lidos ao vivo na janela do jogo. Nada para digitar, nada para manter."),
   ("Quatro idiomas", "Inglês, francês, espanhol e português, seguindo o idioma do seu sistema."),
   ("Funções", "Marque cada personagem como tanque, curandeiro, dano, suporte ou batedor e a fatia dele na roda ganha uma borda colorida. Passando de cinco clientes, cor se lê mais rápido que nome."),
   ("Espiada", "Segure uma tecla para olhar outro cliente, solte e você volta exatamente para onde estava, com sua posição na rotação intacta."),
   ("Ordem por número", "Digite uma posição para colocar um personagem. Ordenar um time por iniciativa são seis toques, não vinte cliques numa seta."),
   ("Fica salvo", "Ordem, times, funções, líder e cada atalho são gravados em disco conforme você muda, por personagem. Volte semana que vem e está igual."),
   ("Fica fora do caminho", "Ele abre os ajustes na primeira vez para você configurar e depois fica quieto na barra de menus. Uma vez rodando, não volta para a frente, nem quando o Launcher da Ankama o reabre."),
   ("Uma tecla, uma ação", "Atribuir uma tecla que outro atalho já tem libera ela lá. Duas ações numa tecla significa que uma nunca dispara."),
   ("Já lá quando você chega", "Inicia no login com um clique, então já está rodando quando você abre o Ankama Launcher. Parado não custa nada, sem nenhum cliente aberto nem consulta o sistema."),
   ("Só o cliente em que você está", "Ligue a ocultação e os outros clientes somem enquanto você joga o da frente. Nada aparece nas bordas, o Command Tab continua legível, e eles voltam assim que você troca para eles."),
 ],
 "names_title": "Ele reconhece seus personagens sozinho",
 "names_body": "Você nunca digita um nome. O Multi-Tofu lê o título da janela do Dofus, então assim que um personagem entra o nome real dele aparece na roda, na barra de menus e nos ajustes. Um cliente aberto mas ainda na tela de login não tem personagem, então aparece como Conta 1, Conta 2 e assim por diante. Eles continuam clicáveis no menu, você pode ir lá fazer login, mas ficam fora da rotação do F1. Uma tecla nunca leva você para uma janela sem personagem.",
 "install_title": "Instalação em um minuto",
 "steps": [
   ("Baixar e descompactar", "Pegue o zip na página de versões e arraste o Multi-Tofu para a pasta Aplicativos."),
   ("Botão direito, Abrir", "O app não é assinado com uma conta paga de desenvolvedor da Apple, então a primeira abertura precisa de botão direito e Abrir. Depois disso abre normalmente."),
   ("Permitir Acessibilidade", "O macOS pede uma vez. O Multi-Tofu precisa dela para ler os títulos das janelas e ouvir seus atalhos. Ative e os atalhos ligam alguns segundos depois, sem reiniciar."),
   ("Atualizar mais tarde", "Um app assinado sem uma conta paga de desenvolvedor Apple muda de assinatura a cada versão, então o macOS para de reconhecê-lo e seus atalhos ficam mudos mesmo com o botão parecendo ligado. Abra os ajustes e clique em Reparar o acesso. Isso redefine a permissão e o macOS pergunta de novo."),
 ],
 "keys_title": "Atalhos padrão",
 "keys": [("Próximo personagem", "F1"), ("Personagem anterior", "F2"), ("Ir para o líder", "F3"),
          ("Procurar janelas", "F4"), ("Roda de personagens", "segurar Option"), ("Espiada em outro cliente", "segurar `"), ("Abrir ajustes", "Control + F1")],
 "keys_note": "Tudo pode ser remapeado. Os atalhos são gravados como códigos de tecla física, então continuam funcionando se você trocar entre AZERTY e QWERTY.",
 "safe_title": "Não automatiza nada",
 "safe_body": "O Multi-Tofu traz janelas para a frente. É só isso que ele faz. Não tem bot, não lê pacotes, não injeta memória e não transmite uma tecla para vários clientes ao mesmo tempo. Toda ação continua vindo de você, em um cliente por vez. O código é público, você não precisa acreditar na nossa palavra.",
 "why_title": "Por que existe",
 "why_body": "No Windows existem o Dosoft e o Organizer. No Mac não existia nada, e o projeto mais próximo foi arquivado em agosto de 2026. O Dosoft é Apache 2.0 mas construído inteiramente sobre a API Win32, então nada dá para portar. Esta é uma implementação nova sobre a API de Acessibilidade do macOS, um CGEventTap para os atalhos e o AppKit para a roda, reaproveitando a arte das classes e o design funcional sob aquela licença.",
 "compat_title": "Requisitos",
 "compat": ["macOS 12 ou mais recente", "Dofus 3 (Unity), o cliente que o Ankama Launcher instala",
            "Apple Silicon ou Intel, uma única build universal", "Modo janela ou sem borda, a roda não desenha sobre tela cheia exclusiva"],
 "footer_docs": "Documentação",
 "footer_issues": "Relatar um problema",
 "footer_licence": "Apache 2.0",
 "disclaimer": "O Multi-Tofu não é afiliado, endossado nem patrocinado pela Ankama Games. DOFUS e todos os nomes e imagens relacionados são propriedade da Ankama Games.",
 "alt_logo": "O ícone do Multi-Tofu, um passarinho redondo cor de creme sobre fundo roxo",
 "alt_wheel": "A roda de personagens do Multi-Tofu, seis personagens de Dofus em círculo com o destacado em evidência",
 "alt_prefs": "A janela de ajustes do Multi-Tofu com os atalhos e a lista de personagens detectados",
},
}
